export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'aaaa',
  headLine: 'aaaaaaaaaaaaaaaa',
  description: '.................................',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/gui-bueno-nobg-2.png'),
  alt: 'AAA',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'background',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'aaaa',
  headLine: 'aaaaaaaaaaaaaaaa',
  description: '.................................',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/gui-bueno-nobg-3.png'),
  alt: 'AAA',
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjThree = {
  id: 'portfolio',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'aaaa',
  headLine: 'aaaaaaaaaaaaaaaa',
  description: '.................................',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/gui-bueno-nobg-1.png'),
  alt: 'AAA',
  dark: true,
  primary: true,
  darkText: true,
};
