export let timelineElements = [
  {
    id: 1,
    title: 'Project Manager',
    location: 'Sao Paulo',
    decription: 'aaaaaaaaaaaaaa',
    date: 'August 18',
    company: 'Walmart',
    icon: 'school',
    companyLogo: '',
  },
  {
    id: 2,
    title: 'Project Manager',
    location: 'Sao Paulo',
    decription: 'aaaaaaaaaaaaaa',
    date: 'August 18',
    company: 'Walmart',
    icon: 'work',
    companyLogo: '',
  },
  {
    id: 3,
    title: 'Project Manager',
    location: 'Sao Paulo',
    decription: 'aaaaaaaaaaaaaa',
    date: 'August 18',
    company: 'Walmart',
    icon: 'school',
    companyLogo: '',
  },
  {
    id: 4,
    title: 'Project Manager',
    location: 'Sao Paulo',
    decription: 'aaaaaaaaaaaaaa',
    date: 'August 18',
    company: 'Walmart',
    icon: 'work',
    companyLogo: '',
  },
];
